openapi: 3.0.0
info:
  version: 1.0.0
  title: Truss API
  description: A security API
  termsOfService: ''
  contact:
    name: Truss Team
    email: info@truss-security.com
    url: https://truss-security.com
servers:
  - url: https://30lf7v2t1i.execute-api.us-west-2.amazonaws.com/dev5
paths:
  /product/search:
    post:
      description: Search for products
      operationId: search products
      requestBody:
        description: >-
          Search parameters are optional. Items matching all search parameters
          will be returned.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchParams'
      responses:
        '200':
          description: search response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /product/create:
    post:
      description: creates a new security product
      operationId: create product
      requestBody:
        description: Create a new security product
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '200':
          description: create product response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /product/{id}:
    get:
      description: Returns a product based on a product ID
      operationId: find product by id
      parameters:
        - name: id
          in: path
          description: ID of product to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: get product response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /product/update/{id}:
    put:
      description: updates a product
      operationId: update product
      requestBody:
        description: Create a new security product
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '204':
          description: product updated
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /product/delete/{id}:
    delete:
      description: deletes a single product based on a product ID
      operationId: delete product
      parameters:
        - name: id
          in: path
          description: ID of product to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: product deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Product:
      allOf:
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
        - $ref: '#/components/schemas/NewProduct'
    NewProduct:
      type: object
      required:
        - name
      properties:
        title:
          type: string
          example: TOR-ExitNodes_New Zealand_06/02/2024 08:00 UTC
        author:
          type: array
          items:
            type: string
          example:
            - TOR Project
            - Community
        type:
          type: string
          example: Indicator
        category:
          type: string
          example: TOR
        source:
          type: string
          example: TOR Project
        pubDate:
          type: string
          example: June 02, 2024
        reference:
          type: array
          items:
            type: string
          example:
            - https://www.torproject.org/
            - https://metrics.torproject.org/collector/recent/exit-lists/
        tags:
          type: array
          items:
            type: string
          example:
            - TOR Project
            - TOR Exit Nodes
            - Truss Automation
            - Hourly
            - IPv4
            - New Zealand
        industry:
          type: array
          items:
            type: string
          example:
            - All
        region:
          type: array
          items:
            type: string
          example:
            - All
            - New Zealand
        indicators:
          type: object
          example:
            IPV4:
              - 188.114.97.7
              - 172.67.148.183
            URL:
              - https://rtattack.baqebei1[dot]online/df/tt
            DOMAIN:
              - aedjakodu24.ee
              - lambhuaexpress.in
              - manchac.com
              - tonitto.com
            SHA256:
              - 44a45c396516a3f2705eaf9751a06d346fcae1864f5521356349ce85e78fd386
              - a467302da10ace0bf96963bcd6bdcd6a4e619e28cd477612988276dfee9f429e
    SearchParams:
      type: object
      properties:
        startdate:
          type: number
          description: return products that were uploaded on or after this date
          format: Unix Epoch Time
          example: 1717377710394
        enddate:
          type: number
          description: return products that were uploaded on or before this date
          format: Unix Epoch Time
          example: 1717379710282
        category:
          type: string
          description: Exact match for category name
          example: Ransomware
        source:
          type: string
          description: Exact match for source name
          example: Cisco Talos
        author:
          type: array
          description: Author name contains any of the strings
          items:
            type: string
          example:
            - Research 6
            - Researcher 8
        title:
          type: string
          description: >-
            Returns products where the product title contains the specified
            string
          example: GhostSec joint ransomware operation
        tags:
          type: array
          description: Return products that contain any of the specified tags
          items:
            type: string
          example:
            - C2
            - AlphV
        validators:
          type: array
          description: Return products that contain any of the specified validators
          items:
            type: string
          example:
            - '0x2f5c1d8e7b3a9'
        industry:
          type: array
          description: Return products that contain any of the specified industries
          items:
            type: string
          example:
            - Government
            - Transport
        region:
          type: array
          description: Return products that contain any of the specified regions
          items:
            type: string
          example:
            - Cuba
            - Argentina
            - Poland
        indicators:
          type: object
          description: Return products that contain any of the specified indicators
          items:
            type: array
            items:
              type: string
          example:
            IPV4:
              - 94.103.91.246
            URL:
              - http://94.103.91.246[/]incrementLaunch
              - http://94.103.91.246[/]addInfection
            FILENAME:
              - '*.ghost'
        limit:
          type: number
          description: maximum number of results to return
          example: 10
        startKey:
          $ref: '#/components/schemas/StartKey'
        scanOldestToNewest:
          type: boolean
          default: false
          description: >-
            Sort order of the products according to the product timestamp (true
            = oldest to newest)
          example: true
    SearchRespose2:
      allOf:
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
        - $ref: '#/components/schemas/Metadata'
        - type: array
          items:
            $ref: '#/components/schemas/Product'
    SearchResponse:
      type: object
      properties:
        $metadata:
          $ref: '#/components/schemas/Metadata'
        Count:
          type: string
        Items:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        LastEvaluatedKey:
          $ref: '#/components/schemas/LastEvaluatedKey'
        ScannedCount:
          type: integer
          format: int32
    Metadata:
      type: object
      properties:
        httpStatusCode:
          type: integer
          format: int32
        requestId:
          type: string
        attempts:
          type: integer
          format: int32
        totalRetryDelay:
          type: integer
          format: int32
    LastEvaluatedKey:
      type: object
      description: >-
        when paging, use the LastEvaluatedKey returned from the previous query
        as the startKey for the next query
      properties:
        GSI2PK:
          type: string
        SK:
          type: string
        PK:
          type: string
        GSI2SK:
          type: string
    StartKey:
      type: object
      description: >-
        when paging, use the LastEvaluatedKey returned from the previous query
        as the startKey for the next query
      properties:
        GSI2PK:
          type: string
          example: Ransomware
        SK:
          type: string
          example: VER#0
        PK:
          type: string
          example: PROD#01HGR5R6S0SQDTAPMJC96ZB5BG
        GSI2SK:
          type: number
          example: 1717377710608
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
